accounts/urls.py
from django.conf.urls.defaults import *

from helpers.utils import replace_urlpattern
from accounts.views import *


urlpatterns = patterns('',
    url(r'^profile/$', profile, name='profile'),
    url(r'^forgot/password/$', forgot_password, name='forgot_password'),
    url(r'^profile/edit/$', edit_profile, name='edit_profile'),
    #url(r'^create/$',create_account, name='create-account'),
    url(r'^login/$', login_user, name="login"),
    url(r'^logout/$', logout_user, name="logout"),
    
    url(r'^personnel/$', all_personnel_types, name="all-personnel-types"),
    url(r'^personnel/all$', all_personnel_types, name="all-personnel-types"),
    url(r'^personnel/add$', add_personnel_type, name="add-personnel-type"),
    url(r'^personnel/delete/(?P<type_id>\d+)$', delete_personnel_type, name="delete-personnel-type"),
    
    url(r'^office/$', all_offices, name="all-offices"),
    url(r'^office/all$', all_offices, name="all-offices"),
    url(r'^office/add$', add_office, name="add-office"),
    
    url(r'^unit/$', all_units, name="all-units"),
    url(r'^unit/all$', all_units, name="all-units"),
    url(r'^unit/add$', add_unit, name="add-unit"),

	url(r'^user/$', all_users, name="all-users"),
    url(r'^user/all$', all_users, name="all-users"),
    url(r'^user/add$', add_user, name="add-user"),
    
    url(r'^manage/$', manage_accounts, name="manage-accounts"),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import url, patterns, include
from django.contrib import admin
from django.views.generic.simple import direct_to_template

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('core.urls')),
    url(r'^a/', include('fileupload.urls')),
    (r'^tinymce/', include('tinymce.urls')),
)

if settings.DEBUG:
	from django.views.static import serve
	_media_url = settings.MEDIA_URL
	if _media_url.startswith('/'):
		_media_url = _media_url[1:]
		urlpatterns += patterns('',
									(r'^%s(?P<path>.*)$' % _media_url,
									serve,
									{'document_root': settings.MEDIA_ROOT}))
	del(_media_url, serve)

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models
from imagekit.models import ImageModel
import os
import datetime

GENDER = (
    (u'Male', u'Male'),
    (u'Female', u'Female'),
)

def upload_to(instance, filename):
    name, dot, ext = filename.rpartition('.')
    name = "{0}.{1}".format(instance.user.username, ext)
    return os.path.join('profiles', name)

class Unit(models.Model):
	name = models.CharField(max_length=120, verbose_name="UP Unit", unique=True)
	
	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="unit_created_by")
	modified = models.DateTimeField(default=datetime.datetime.now())
	modified_by = models.ForeignKey(User, verbose_name="modified by", related_name="unit_modified_by", blank=True, null=True)

	class Meta:
		verbose_name = "UP Unit"
		verbose_name_plural = "UP Units"

	def __unicode__(self):
		return self.name

class PersonnelType(models.Model):
	name = models.CharField(max_length=120, verbose_name="Personnel Type", unique=True)
	
	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="type_created_by")
	modified = models.DateTimeField(default=datetime.datetime.now())
	modified_by = models.ForeignKey(User, verbose_name="modified by", related_name="type_modified_by", blank=True, null=True)
	
	class Meta:
		verbose_name = "Personnel Type"
		verbose_name_plural = "Personnel Types"
		
	def __unicode__(self):
		return self.name

class Office(models.Model):
	name = models.CharField(max_length=120, verbose_name="Office Name")
	unit = models.ForeignKey(Unit, verbose_name="UP Unit")
	
	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="office_created_by")
	modified = models.DateTimeField(default=datetime.datetime.now())
	modified_by = models.ForeignKey(User, verbose_name="modified by", related_name="office_modified_by", blank=True, null=True)
	
	class Meta:
		verbose_name = "Office"
		verbose_name_plural = "Offices"
		unique_together = ('name','unit')
		
	def __unicode__(self):
		return self.name

class UserProfile(ImageModel):
    user  = models.OneToOneField(User, verbose_name="User")
    bio   = models.TextField("About Me", blank=True, null=True)
    image = models.ImageField("Photo", upload_to=upload_to, storage=settings.UPLOAD_STORAGE, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    gender = models.CharField(verbose_name="Gender", max_length=6, choices=GENDER, blank=True, null=True)
    
    # better a foreign key to some predefined lists
    city = models.CharField("City", max_length=30, blank=True, null=True)    
    country = models.CharField("Country", max_length=30, blank=True, null=True)
    
    personnel_type = models.ForeignKey(PersonnelType, verbose_name="Type", blank=True, null=True)
    office = models.ForeignKey(Office, verbose_name="Office", blank=True, null=True)
    
    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"
    
    class IKOptions:
        spec_module = 'core.specs'
        image_field = 'image'    
        cache_dir   = 'cache'
    
    def __unicode__(self):
        return u"{0}'s profile".format(self.user.username)

    @property
    def fullname(self):
        return self.user.get_full_name()
    
    @property
    def email(self):
        return self.user.email
    
    @property
    def age(self):
        import datetime
        return int((datetime.date.today() - self.birthday).days / 365.25  )
    
    @property
    def location(self):
        if self.city and self.country:
            return "{0}, {1}".format(self.city, self.country)
        else:
            return None

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

accounts/forms.py
from django import forms
from accounts.models import UserProfile, PersonnelType, Office, Unit
from django.forms.extras.widgets import SelectDateWidget
from datetime import date

from django.contrib.auth.models import User
from django.forms.models import inlineformset_factory

year  = date.today().year
YEARS = range(year-16, year-100, -1) # only let people aged 18-100 register.        

class UserForm(forms.ModelForm):
	username = forms.CharField(max_length=30)
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'name':'password1','title':'Password'}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'name':'password2','title':'Retype Password'}))
	first_name = forms.CharField(max_length=30)
	last_name  = forms.CharField(max_length=30)
	email = forms.EmailField()
	birthday = forms.DateField(widget=SelectDateWidget(years=YEARS), required=False)
	
	class Meta:
		model = UserProfile
		fields  = ('username','password1','password2','personnel_type','office','first_name', 'last_name', 'email' ,'birthday', 'gender', 'city', 'country')
        #widgets = {'birthday': SelectDateWidget(years=YEARS)}

class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30)
    last_name  = forms.CharField(max_length=30)
    email = forms.EmailField()
    
    
    class Meta:
        model   = UserProfile
        fields  = ('first_name', 'last_name', 'email' ,'birthday', 'gender', 'city', 'country', 'bio', 'image')
        widgets = {'birthday': SelectDateWidget(years=YEARS)}
        
        
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.fields['bio'].label = "About Me"
        for key in ['birthday', 'city', 'country']:
            self.fields[key].required = True
            
        
    def save(self, force_insert=False, force_update=False, commit=True):
        profile = super(EditProfileForm, self).save()
        profile.user.first_name = self.cleaned_data['first_name']
        profile.user.last_name  = self.cleaned_data['last_name']
        profile.user.email  = self.cleaned_data['email']
        profile.user.save()
        return profile

class PersonnelTypeForm(forms.ModelForm):
	class Meta:
		model = PersonnelType
		fields = ('name',)
		
class UnitForm(forms.ModelForm):
	class Meta:
		model = Unit
		fields = ('name',)

class OfficeForm(forms.ModelForm):
	class Meta:
		model = Office
		fields = ('name','unit',)

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from helpers import *
from django.shortcuts import render_to_response
from django.template import RequestContext
from accounts.forms import EditProfileForm, PersonnelTypeForm, OfficeForm, UnitForm, UserForm
from accounts.models import UserProfile, PersonnelType, Office, Unit
from django.core.mail import send_mail, EmailMessage
from datetime import date

@render_to('home.html')
def profile(request, username=''):    
    mine = False
    if username == '':
        if request.user.is_authenticated():
            profile = request.user.get_profile()
            mine = True
        else:
            return reverse_redirect('index')
    else:
        user = get_object_or_404(User, username=username)
        profile = user.get_profile()
        me = UserProfile.objects.get(user=request.user)
        if user == request.user:
            mine = True
    
    return {'profile': profile, 'mine': mine}
    
    
@login_required
@render_to('accounts/edit_profile.html')
def edit_profile(request):
    
    profile = request.user.get_profile()
    initial = { 'first_name': profile.user.first_name, 'last_name': profile.user.last_name, 'email': profile.user.email }
    if request.method == "POST":
        form = EditProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
           form.save()
           return reverse_redirect('profile')         
    else:
        form = EditProfileForm(initial=initial, instance=profile)
    
    return {'form': form, 'formset':formset}
    
    
    
def update_user(sender, user, request, **kwargs):
    ''' This will only be called when the registration form has validated 
        so we assume it is safe to utilize the POST parameters
    '''
    if request.method == 'POST':    
        user.first_name = request.POST.get('first_name')
        user.last_name  = request.POST.get('last_name')
        user.save()
        
        y = request.POST.get('birthday_year')
        m = request.POST.get('birthday_month')
        d = request.POST.get('birthday_day')
        profile = user.get_profile()
        profile.birthday = date(int(y), int(m), int(d))
        profile.save()

#signals.user_registered.connect(update_user, sender=None, weak=False, dispatch_uid="accounts_views_update_user")

@render_to('accounts/forgot_password.html')
def forgot_password(request):
    if request.method == 'POST':
        user = get_object_or_None(User, email=request.POST['email'])
        if user:
            pass
    return {'forgot': True}

@render_to('registration/login.html')
def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return reverse_redirect('home')
	return {'login':'login'}

def logout_user(request):
	logout(request)
	return reverse_redirect('home')

@render_to('accounts/all_users.html')
@login_required
def all_users(request):
	users = UserProfile.objects.filter(user__is_active=True)
	return {'users':users}

@render_to('accounts/add_user.html')
@login_required
def add_user(request):
	if request.user.is_authenticated and request.user.is_superuser:
		form = UserForm()
		if request.method == 'POST':
			form = UserForm(data=request.POST)
			username = request.POST['username']
			email = request.POST['email']
			if form.is_valid():
				user = form.save(commit=False)
		return {'form':form}
	return render_to_response("home.html",{'404':'404'},
            context_instance=RequestContext(request))

@render_to('accounts/all_personnel_types.html')
@login_required
def all_personnel_types(request):
	types = PersonnelType.objects.all()
	return {'types':types}

@render_to('accounts/add_personnel_type.html')
@login_required
def add_personnel_type(request):
	form = PersonnelTypeForm()
	if request.method == "POST":
		form = PersonnelTypeForm(data=request.POST)
		if form.is_valid():
			type = form.save(commit=False)
			type.created_by = type.modified_by = request.user
			type.save()
			return reverse_redirect('all-personnel-types')
	return {'form':form}
	
@login_required
def delete_personnel_type(request, type_id=None):
	if request.user.is_superuser:
		type = get_object_or_None(PersonnelType, pk=type_id)
		if type:
			type.delete()
	return reverse_redirect('all-personnel-types')

@render_to('accounts/all_offices.html')
@login_required
def all_offices(request):
	offices = Office.objects.all()
	units = Unit.objects.all()
	return {'offices':offices, 'units':units}

@render_to('accounts/add_office.html')
@login_required
def add_office(request):
	form = OfficeForm()
	if request.method == "POST":
		form = OfficeForm(data=request.POST)
		if form.is_valid():
			type = form.save(commit=False)
			type.created_by = type.modified_by = request.user
			type.save()
			return reverse_redirect('all-offices')
	return {'form':form}

@render_to('accounts/all_units.html')
@login_required
def all_units(request):
	units = Unit.objects.all().order_by('name')
	return {'units':units}

@render_to('accounts/add_unit.html')
@login_required
def add_unit(request):
	form = UnitForm()
	if request.method == "POST":
		form = UnitForm(data=request.POST)
		if form.is_valid():
			unit = form.save(commit=False)
			unit.created_by = unit.modified_by = request.user
			unit.save()
			return reverse_redirect('all-units')
	return {'form':form}

@render_to('accounts/manage-accounts.html')
@login_required
def manage_accounts(request):
	return {'None':'None'}

templates/accounts/add_office.html
{% extends 'base.html' %}

{% block body %}
	<div>
		<form action="" method="post">{% csrf_token %}
			{% for field in form %}
			<div>
				<span>{{ field.label_tag }}</span>{{ field }}
			</div>
			{% endfor %}
			<div><input type="submit" value="Add" /></div>
		</form>
	</div>
{% endblock %}

templates/accounts/add_personnel_type.html
{% extends 'base.html' %}

{% block body %}
	<div>
		<form action="" method="post">{% csrf_token %}
			{% for field in form %}
			<div>
				<span>{{ field.label_tag }}</span>{{ field }}
			</div>
			{% endfor %}
			<div><input type="submit" value="Add" /></div>
		</form>
	</div>
{% endblock %}

templates/accounts/add_unit.html
{% extends 'base.html' %}

{% block body %}
	<div>
		<form action="" method="post">{% csrf_token %}
			{% for field in form %}
			<div>
				<span>{{ field.label_tag }}</span>{{ field }}
			</div>
			{% endfor %}
			<div><input type="submit" value="Add" /></div>
		</form>
	</div>
{% endblock %}

templates/accounts/add_user.html
{% extends 'base.html' %}

{% block js %}
<script>
	$(document).ready(function(){
		$("#id_submit").click(function(){
			alert('Submit!');
		});
	});
</script>
{% endblock %}

{% block body %}
	<div>
		<form action="" method="post">{% csrf_token %}
			{% for field in form %}
			<div>
				<span>{{ field.label_tag }}</span>{{ field }}
				{% if field.help_text %} <span>{{field.help_text}}</span> {% endif %}
			</div>
			{% endfor %}
			<div><input type="button" value="Add" id="id_submit" /></div>
		</form>
	</div>
{% endblock %}

templates/accounts/all_offices.html
{% extends 'base.html' %}

{% block title %} Offices {% endblock %}

{% block js %}
	<script>
		$(document).ready(function(){
			var elem = $(this).find('.add-folder');
			$(elem).hide();
			$(this).find('.manage-actions a.last').click(function(){
				var d = $(elem).css('display');
				if(d == 'none'){
					$(elem).show("slide", { direction: "left" }, 500);
				}else{
					$(elem).hide("slide", { direction: "left" }, 500);
				}
			});
		});
	</script>
{% endblock %}

{% block body %}
	<div class="home"><span class="title">Manage Accounts</span></div>
	<div class="line-spacer"></div>
	<div class="manage">
		<a href="{% url all-users %}"><div class="type"><div class="img"></div><span>Users</span></div></a>
		<a href="{% url all-units %}"><div class="type"><div class="img"></div><span>Units</span></div></a>
		<a href="{% url all-offices %}"><div class="type active"><div class="img"></div><span>Offices</span></div></a>
		<a href="{% url all-personnel-types %}"><div class="type"><div class="img"></div><span>User Types</span></div></a>
	</div>
	<div id="clear-both"></div>
	<div class="manage-actions">
		<a class="last">Add Office</a>
		<div class="add-folder">
			<form method="POST" action="{% url add-office %}">{% csrf_token %}
				<input id="id_name" type="text" name="name" maxlength=120 placeholder="Enter office name here" />
				<select name="unit" id="id_unit">
					
					<option value="" selected="selected">Choose UP Unit</option>
					{% for unit in units %}
						<option value="{{unit.id}}">{{unit}}</option>
					{% endfor %}
				</select>
				<input type='submit' value='Add' />
			</form>
		</div>
	</div>
	<br />
	<div id="clear-both"></div>
	<div class="line-spacer"></div>
	<div class="accounts-body">
		{% for office in offices %}
			<div class="account">
				<a href="">{{ office }}</a>
				<div class="close {{office.id}}">X</div>
			</div>
		{% endfor %}
		<div id="clear-both"></div>
	</div>
{% endblock %}

templates/accounts/all_personnel_types.html
{% extends 'base.html' %}

{% block title %} User Types {% endblock %}

{% block js %}
	<script>
		$(document).ready(function(){
			var elem = $(this).find('.add-folder');
			$(elem).hide();
			$(this).find('.manage-actions a.last').click(function(){
				var d = $(elem).css('display');
				if(d == 'none'){
					$(elem).show("slide", { direction: "left" }, 500);
				}else{
					$(elem).hide("slide", { direction: "left" }, 500);
				}
			});
		});
	</script>
{% endblock %}

{% block body %}
	<div class="home"><span class="title">Manage Accounts</span></div>
	<div class="line-spacer"></div>
	<div class="manage">
		<a href="{% url all-users %}"><div class="type"><div class="img"></div><span>Users</span></div></a>
		<a href="{% url all-units %}"><div class="type"><div class="img"></div><span>Units</span></div></a>
		<a href="{% url all-offices %}"><div class="type"><div class="img"></div><span>Offices</span></div></a>
		<a href="{% url all-personnel-types %}"><div class="type active"><div class="img"></div><span>User Types</span></div></a>
	</div>
	<div id="clear-both"></div>
	<div class="manage-actions">
		<a class="last">Add User Type</a>
		<div class="add-folder">
			<form method="POST" action="{% url add-personnel-type %}">{% csrf_token %}
				<input id="id_name" type="text" name="name" maxlength=120 placeholder="Enter user type here" />
				<input type='submit' value='Add' />
			</form>
		</div>
	</div>
	<br />
	<div id="clear-both"></div>
	<div class="line-spacer"></div>
	<div class="accounts-body">
		{% for type in types %}
			<div class="account">
				<a href="">{{ type }}</a>
				<div class="close {{type.id}}">X</div>
			</div>
		{% endfor %}
		<div id="clear-both"></div>
	</div>
{% endblock %}

templates/accounts/all_units.html
{% extends 'base.html' %}

{% block title %} Units {% endblock %}

{% block js %}
	<script>
		$(document).ready(function(){
			var elem = $(this).find('.add-folder');
			$(elem).hide();
			$(this).find('.manage-actions a.last').click(function(){
				var d = $(elem).css('display');
				if(d == 'none'){
					$(elem).show("slide", { direction: "left" }, 500);
				}else{
					$(elem).hide("slide", { direction: "left" }, 500);
				}
			});
		});
	</script>
{% endblock %}

{% block body %}
	<div class="home"><span class="title">Manage Accounts</span></div>
	<div class="line-spacer"></div>
	<div class="manage">
		<a href="{% url all-users %}"><div class="type"><div class="img"></div><span>Users</span></div></a>
		<a href="{% url all-units %}"><div class="type active"><div class="img"></div><span>Units</span></div></a>
		<a href="{% url all-offices %}"><div class="type"><div class="img"></div><span>Offices</span></div></a>
		<a href="{% url all-personnel-types %}"><div class="type"><div class="img"></div><span>User Types</span></div></a>
	</div>
	<div id="clear-both"></div>
	<div class="manage-actions">
		<a class="last">Add Unit</a>
		<div class="add-folder">
			<form method="POST" action="{% url add-unit %}">{% csrf_token %}
				<input id="id_name" type="text" name="name" maxlength=120 placeholder="Enter UP unit here" />
				<input type='submit' value='Add' />
			</form>
		</div>
	</div>
	<br />
	<div id="clear-both"></div>
	<div class="line-spacer"></div>
	<div class="accounts-body">
		{% for unit in units %}
			<div class="account">
				<a href="">{{ unit }}</a>
				<div class="close {{unit.id}}">X</div>
			</div>
		{% endfor %}
		<div id="clear-both"></div>
	</div>
{% endblock %}

templates/accounts/all_users.html
{% extends 'base.html' %}

{% block title %} Users {% endblock %}

{% block js %}
	<script>
		$(document).ready(function(){
		});
	</script>
{% endblock %}

{% block body %}
	<div class="home"><span class="title">Manage Accounts</span></div>
	<div class="line-spacer"></div>
	<div class="manage">
		<a href="{% url all-users %}"><div class="type active"><div class="img"></div><span>Users</span></div></a>
		<a href="{% url all-units %}"><div class="type"><div class="img"></div><span>Units</span></div></a>
		<a href="{% url all-offices %}"><div class="type"><div class="img"></div><span>Offices</span></div></a>
		<a href="{% url all-personnel-types %}"><div class="type"><div class="img"></div><span>User Types</span></div></a>
	</div>
	<div id="clear-both"></div>
	<div class="manage-actions">
		<a class="last" href="{% url add-user %}">Add User</a>
	</div>
	<br />
	<div id="clear-both"></div>
	<div class="line-spacer"></div>
	<div class="accounts-body">
		{% for user in users %}
			<div class="account">
				<a href="">{{ user }}</a>
				<div class="close {{user.id}}">X</div>
			</div>
		{% endfor %}
		<div id="clear-both"></div>
	</div>
{% endblock %}

templates/accounts/manage-accounts.html
{% extends 'base.html' %}

{% block title %} Manage Accounts {% endblock %}

{% block js %}
	<script>
		$(document).ready(function(){
		});
	</script>
{% endblock %}

{% block body %}
	<div class="home"><span class="title">Manage Accounts</span></div>
	<div class="line-spacer"></div>
	<div class="manage">
		<a href="{% url all-users %}"><div class="type"><div class="img"></div><span>Users</span></div></a>
		<a href="{% url all-units %}"><div class="type"><div class="img"></div><span>Units</span></div></a>
		<a href="{% url all-offices %}"><div class="type"><div class="img"></div><span>Offices</span></div></a>
		<a href="{% url all-personnel-types %}"><div class="type"><div class="img"></div><span>User Types</span></div></a>
	</div>
{% endblock %}