urls.py
from django.conf import settings
from django.conf.urls.defaults import url, patterns, include
from django.contrib import admin
from django.views.generic.simple import direct_to_template

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('core.urls')),
    url(r'^a/', include('fileupload.urls')),
    (r'^tinymce/', include('tinymce.urls')),
)

if settings.DEBUG:
	from django.views.static import serve
	_media_url = settings.MEDIA_URL
	if _media_url.startswith('/'):
		_media_url = _media_url[1:]
		urlpatterns += patterns('',
									(r'^%s(?P<path>.*)$' % _media_url,
									serve,
									{'document_root': settings.MEDIA_ROOT}))
	del(_media_url, serve)

core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from accounts.models import UserProfile, PersonnelType, Office
from helpers import *
import datetime

fs = FileSystemStorage(location="private/")

def validate_file_extension(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError(u'Error message')

class Folder(models.Model):
	name = models.CharField(max_length=120, verbose_name="Folder Name", unique=True)
	parent = models.ForeignKey('self', verbose_name="Parent Folder", blank=True, null=True)
	
	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="folder_created_by")
	last_viewed = models.DateTimeField(default=datetime.datetime.now())
	last_viewed_by = models.ForeignKey(User, verbose_name="Last Viewed by", related_name="folder_last_viewed_by")
	
	def __unicode__(self):
		if self.parent:
			return "{0} - {1}".format(self.parent.name, self.name)
		else:
			return "{0}".format(self.name)

class FileUpload(models.Model):
	filename = models.CharField(max_length=120, verbose_name="File Name", unique=True)
	folder = models.ForeignKey(Folder, verbose_name="Folder", blank=True, null=True)
	file = models.FileField(storage=fs, upload_to=fs, validators=[validate_file_extension])
	public = models.BooleanField(default=True)

	allowed_personnels = models.ManyToManyField(PersonnelType, related_name="file_allowed_personnel", blank=True, null=True)
	allowed_offices = models.ManyToManyField(Office, related_name="file_allowed_offices", blank=True, null=True)
	allowed_users = models.ManyToManyField(User, related_name="file_allowed_users", blank=True, null=True)

	uploaded = models.DateTimeField(default=datetime.datetime.now())
	uploaded_by = models.ForeignKey(User, verbose_name="Uploaded by", related_name="file_uploaded_by")
	last_viewed = models.DateTimeField(default=datetime.datetime.now())
	last_viewed_by = models.ForeignKey(User, verbose_name="Last Viewed by", related_name="file_last_viewed_by")
	
	def is_allowed(self, username):
		user = get_object_or_None(User, username=username)
		if user:
			if user in self.allowed_users:
				return True
			elif user.office in self.allowed_offices:
				return True
			elif user.personnel_type in self.allowed_personnels:
				return True
			else:
				return False
		else:
			return False

	def is_private(self):
		return (not public)

	def __unicode__(self):
		return self.filename
	
class BORPosition(models.Model):
	name = models.CharField(max_length=120, verbose_name="Position")
	rank = models.PositiveIntegerField(default=0)
	
	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="borposition_created_by")
	modified = models.DateTimeField(default=datetime.datetime.now())
	modified_by = models.ForeignKey(User, verbose_name="Modified by", related_name="borposition_modified_by")
	
	class Meta:
		verbose_name = "BOR Position"
		verbose_name_plural = "BOR Positions"
	
	def __unicode__(self):
		return self.name

class BOR(models.Model):
	first_name = models.CharField(max_length=120)
	middle_name = models.CharField(max_length=120, blank=True, null=True)
	last_name = models.CharField(max_length=120)
	description = models.CharField(verbose_name="Position/Office", max_length=400)
	bor_position = models.ForeignKey(BORPosition, verbose_name="Position")

	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="bor_created_by")
	modified = models.DateTimeField(default=datetime.datetime.now())
	modified_by = models.ForeignKey(User, verbose_name="Modified by", related_name="bor_modified_by")
	
	class Meta:
		verbose_name = "Board of Regent"
		verbose_name_plural = "Board of Regents"
	
	def __unicode__(self):
		return "{0}, {1} {2}".format(self.last_name, self.first_name, self.middle_name)

class Announcement(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	
	active = models.BooleanField(default=True)
	
	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="announcement_created_by")
	modified = models.DateTimeField(default=datetime.datetime.now())
	modified_by = models.ForeignKey(User, verbose_name="Modified by", related_name="announcement_modified_by")
	
	def __unicode__(self):
		return self.title

class Page(models.Model):
	name = models.CharField(max_length=120)
	title = models.CharField(max_length=32)
	content = models.TextField()
	
	created = models.DateTimeField(default=datetime.datetime.now())
	created_by = models.ForeignKey(User, verbose_name="Created by", related_name="page_created_by")
	modified = models.DateTimeField(default=datetime.datetime.now())
	modified_by = models.ForeignKey(User, verbose_name="Modified by", related_name="page_modified_by")
	
	def __unicode__(self):
		return self.name

templates/about.html
{% extends 'base.html' %}
{% load wysiwyg %}

{% block title  %} About {% endblock %}

{% block js %}
    <script type="text/javascript">
		$(document).ready(function() {
		});
	</script>
{% endblock %}

{% block body %}

    <div class="home">
		{% if not form %}
			<div class="no-font-style">
				{% autoescape off %}
					{{ page.content }}
				{% endautoescape %}
			</div>
			<a href="{% url edit-page 'about' %}">Edit</a>
		{% endif %}
		
		<div id="clear-both"></div>
		
		{% if form %}
			{% wysiwyg_setup %}
			<form class="wysiwyg" action="{% url edit-page 'about' %}" method="post">{% csrf_token %}
				<input type="hidden" id='id_name' name='name' value="about"/>
				<textarea id="id_content" name="content">
					{% autoescape off %}
						{{ page.content }}
					{% endautoescape %}
				</textarea>
				<br />
				<input type="submit" value="Submit" />
			{% wysiwyg_editor "id_content" %}
			</form>
			
		{% endif %}
		
	</div>
	
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>OSU | {% block title %}{% endblock %}</title>
        <link rel="shortcut icon" href="{{MEDIA_URL}}images/favicon.ico" >
        <link href="{{MEDIA_URL}}style.css" rel="stylesheet" type="text/css" />
        <script src="{{MEDIA_URL}}js/jquery.min.js"></script>
        <script src="{{MEDIA_URL}}js/jquery-ui.min.js"></script>
        <script src="{{MEDIA_URL}}js/dropdown.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}tiny_mce/tiny_mce.js"></script>
        <link href='http://fonts.googleapis.com/css?family=Dosis:200,400,600,700' rel='stylesheet' type='text/css'>
        <script>
            $.ajaxSetup({ 
                 beforeSend: function(xhr, settings) {
                     function getCookie(name) {
                         var cookieValue = null;
                         if (document.cookie && document.cookie != '') {
                             var cookies = document.cookie.split(';');
                             for (var i = 0; i < cookies.length; i++) {
                                 var cookie = jQuery.trim(cookies[i]);
                                 // Does this cookie string begin with the name we want?
                             if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                 cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                 break;
                             }
                         }
                     }
                     return cookieValue;
                     }
                     if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                         // Only send the token to relative URLs i.e. locally.
                         xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                     }
                 } 
            });
            
            $(document).ready(function(){
                var h = window.innerHeight;
                $(".body").css('min-height', h-335);
            });
        </script>
        {% block js  %}{% endblock %}
        {% block css %}{% endblock %}
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="links">
				<div class="left">
					<div class="link"><a href="{% url open-page 'home' %}">Home</a></div>
					<div class="link"><a href="{% url open-page 'about' %}">About</a></div>
					<div class="link"><a href="{% url open-page 'contact' %}">Contact</a></div>
				</div>
				<div class="right">
					
				</div>
            </div>
        </header>
        <div style="clear:both"></div>
        <div class="banner">
			<div class="wrapper">
				<a href="/">Office of the Secretary of the University and of the Board of Regents</a>
            </div>
        </div>
		<div class="bodywrapper">
			<nav>
				<div class="main">
					<a href="{% url open-page 'home' %}"><div class="link">Home</div></a>
					<a href="{% url open-page 'about' %}"><div class="link">About OSU</div></a>
					<a href="{% url open-page 'boardofregents' %}"><div class="link">The UP Board of Regents</div></a>
					<a href="{% url gazette %}"><div class="link">The UP Gazette</div></a>
					<a href="{% url all-announcements %}"><div class="link">Announcements</div></a>
					<a href="{% url open-page 'contact' %}"><div class="link">Contact Us</div></a>
				</div>
				{% if request.user.is_superuser %}
				<div class="extras">
					<span>Extras</span>
					<a href="{% url main-folders %}">File Browser</a>
					<!--<a href="{% url manage-accounts %}">Manage Accounts</a>-->
				</div>
				{% endif %}
			</nav>
			<div class="body">
				{% block body %}{% endblock %}
			</div>
			<div style="clear:both"></div>
        </div>
        <footer>
			<div class="wrapper left">
				{% if request.user.is_authenticated %}
					<span>logged in as {{request.user}}</span>
					<span><a href="{% url logout %}">Logout</a></span>
				{% else %}
					<span><a href="{% url login %}">Login</a></span>
				{% endif %}
				<span><a href="/admin/">Site Admin</a></span>
			</div>
            <div class="wrapper right">
				<span>Copyright © 2009-2012 OSUweb. All Rights Reserved.</span>
			</div>
        </footer>
        <div style="clear:both"></div>
    </body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load wysiwyg %}

{% block title  %} Contact {% endblock %}

{% block js %}
    <script type="text/javascript">
		$(document).ready(function() {
		});
	</script>
{% endblock %}

{% block body %}

    <div class="home">
		{% if not form %}
			<div class="no-font-style">
				{% autoescape off %}
					{{ page.content }}
				{% endautoescape %}
			</div>
			<a href="{% url edit-page 'contact' %}">Edit</a>
		{% endif %}
		
		<div id="clear-both"></div>
		
		{% if form %}
			{% wysiwyg_setup %}
			<form class="wysiwyg" action="{% url edit-page 'contact' %}" method="post">{% csrf_token %}
				<input type="hidden" id='id_name' name='name' value="contact" />
				<textarea id="id_content" name="content">
					{% autoescape off %}
						{{ page.content }}
					{% endautoescape %}
				</textarea>
				<br />
				<input type="submit" value="Submit" />
			{% wysiwyg_editor "id_content" %}
			</form>
			
		{% endif %}
		<div id="clear-both"></div>
	</div>
	<div id="clear-both"></div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load wysiwyg %}

{% block title  %} Home {% endblock %}

{% block js %}
    <script type="text/javascript">
		$(document).ready(function() {
		});
	</script>
{% endblock %}

{% block body %}
	
    <div class="home">
		
    </div>
    
    <div id="clear-both"></div>
{% endblock %}

templates/old_base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>OSU | {% block title %}{% endblock %}</title>
        <link rel="shortcut icon" href="{{MEDIA_URL}}images/favicon.ico" >
        <link href="{{MEDIA_URL}}style.css" rel="stylesheet" type="text/css" />
        <script src="{{MEDIA_URL}}js/jquery.min.js"></script>
        <script src="{{MEDIA_URL}}js/jquery-ui.min.js"></script>
        <script src="{{MEDIA_URL}}js/dropdown.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}tiny_mce/tiny_mce.js"></script>
        <link href='http://fonts.googleapis.com/css?family=Dosis:200,400,600,700' rel='stylesheet' type='text/css'>
        <script>
            $.ajaxSetup({ 
                 beforeSend: function(xhr, settings) {
                     function getCookie(name) {
                         var cookieValue = null;
                         if (document.cookie && document.cookie != '') {
                             var cookies = document.cookie.split(';');
                             for (var i = 0; i < cookies.length; i++) {
                                 var cookie = jQuery.trim(cookies[i]);
                                 // Does this cookie string begin with the name we want?
                             if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                 cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                 break;
                             }
                         }
                     }
                     return cookieValue;
                     }
                     if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                         // Only send the token to relative URLs i.e. locally.
                         xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                     }
                 } 
            });
            
            $(document).ready(function(){
                var h = window.innerHeight;
                $(".body").css('min-height', h-335);
            });
        </script>
        {% block js  %}{% endblock %}
        {% block css %}{% endblock %}
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="links">
				<div class="left">
					<div class="link"><a href="{% url open-page 'home' %}">Home</a></div>
					<div class="link"><a href="{% url open-page 'about' %}">About</a></div>
					<div class="link"><a href="{% url open-page 'contact' %}">Contact</a></div>
				</div>
				<div class="right">
					
				</div>
            </div>
        </header>
        <div style="clear:both"></div>
        <div class="banner">
			<div class="wrapper">
				<a href="/">Office of the Secretary of the University and of the Board of Regents</a>
            </div>
        </div>
		<div class="bodywrapper">
			<nav>
				<div class="main">
					<a href="{% url open-page 'home' %}"><div class="link">Home</div></a>
					<a href="{% url open-page 'about' %}"><div class="link">About OSU</div></a>
					<a href="{% url open-page 'boardofregents' %}"><div class="link">The UP Board of Regents</div></a>
					<a href="{% url gazette %}"><div class="link">The UP Gazette</div></a>
					<a href="{% url all-announcements %}"><div class="link">Announcements</div></a>
					<a href="{% url open-page 'contact' %}"><div class="link">Contact Us</div></a>
				</div>
				{% if request.user.is_superuser %}
				<div class="extras">
					<span>Extras</span>
					<a href="{% url main-folders %}">File Browser</a>
					<!--<a href="{% url manage-accounts %}">Manage Accounts</a>-->
				</div>
				{% endif %}
			</nav>
			<div class="body">
				{% block body %}{% endblock %}
			</div>
			<div style="clear:both"></div>
        </div>
        <footer>
			<div class="wrapper left">
				{% if request.user.is_authenticated %}
					<span>logged in as {{request.user}}</span>
					<span><a href="{% url logout %}">Logout</a></span>
				{% else %}
					<span><a href="{% url login %}">Login</a></span>
				{% endif %}
				<span><a href="/admin/">Site Admin</a></span>
			</div>
            <div class="wrapper right">
				<span>Copyright © 2009-2012 OSUweb. All Rights Reserved.</span>
			</div>
        </footer>
        <div style="clear:both"></div>
    </body>
</html>